import { PlanType } from "@/types"

export const ThemeColor = {
  system: [
    "#FFFFFF",
    "#FCFCFD",
    "#F9FAFB",
    "#F0F1F4",
    "#E8E9ED",
    "#DFE1E6",
    "#D8DBE0",
    "#CED2D9",
    "#B8BCC6",
    "#8A8E99",
    "#7E828C",
    "#5B5F6B",
    "#1A1A26",
  ],
  primary: [
    "",
    "#FFFCFC",
    "#FFF9F9",
    "#FFEBEA",
    "#FFDAD8",
    "#FFC8C5",
    "#FFB9B4",
    "#FFA6A0",
    "#FF8D82",
    "#FF4242",
    "#E93D48",
    "#D5143A",
    "#5E121E",
  ],
  secondary: [
    "",
    "#F7FFFF",
    "#F0FEFF",
    "#E0F7FA",
    "#CCEFF5",
    "#ACDFEA",
    "#8DD0E0",
    "#68BFD3",
    "#40A1B8",
    "#48B9D7",
    "#3AA4BF",
    "#0094BD",
    "#133F4D",
  ],
  success: ["", "#F5FCF3", "#DBF8D1", "#BAE9A9", "#7ACD5C", "#72CB51", "#234816"],
  info: ["", "#F3FAFC", "#D1EFF8", "#A9DBE9", "#5CB5CD", "#007A93", "#163E48"],
  error: ["", "#FFF7F6", "#FFDBD6", "#FFBAB2", "#F5897F", "#F12E33", "#691213"],
  warning: ["", "#FCF7F3", "#F8E1D1", "#E9C8A9", "#CD8B5C", "#933D00", "#482B16"],
  rating: ["", "#FCF9F3", "#F8EBD1", "#E9D4A9", "#F5BD4C", "#936200", "#483716"],
}

export const PlanList = [
  {
    type: PlanType.Business,
    titleKey: "business.title",
    priceKey: "business.price",
    featuresKeys: ["business.features.0", "business.features.1", "business.features.2", "business.features.3"],
  },
  {
    type: PlanType.BusinessPlus,
    titleKey: "businessPlus.title",
    priceKey: "businessPlus.price",
    featuresKeys: [
      "businessPlus.features.0",
      "businessPlus.features.1",
      "businessPlus.features.2",
      "businessPlus.features.3",
      "businessPlus.features.4",
      "businessPlus.features.5",
      "businessPlus.features.6",
    ],
    currency: "businessPlus.currency",
    period: "businessPlus.period",
  },
  {
    type: PlanType.Company,
    titleKey: "company.title",
    priceKey: "company.price",
    featuresKeys: [
      "company.features.0",
      "company.features.1",
      "company.features.2",
      "company.features.3",
      "company.features.4",
      "company.features.5",
    ],
    currency: "company.currency",
    period: "company.period",
  },
]
