/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
    "*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          1: "hsl(var(--primary-1))",
          2: "hsl(var(--primary-2))",
          3: "hsl(var(--primary-3))",
          4: "hsl(var(--primary-4))",
          5: "hsl(var(--primary-5))",
          6: "hsl(var(--primary-6))",
          7: "hsl(var(--primary-7))",
          8: "hsl(var(--primary-8))",
          9: "hsl(var(--primary-9))",
          10: "hsl(var(--primary-10))",
        },
        secondary: {
          1: "hsl(var(--secondary-1))",
          2: "hsl(var(--secondary-2))",
          3: "hsl(var(--secondary-3))",
          4: "hsl(var(--secondary-4))",
          5: "hsl(var(--secondary-5))",
          6: "hsl(var(--secondary-6))",
          7: "hsl(var(--secondary-7))",
          8: "hsl(var(--secondary-8))",
          9: "hsl(var(--secondary-9))",
          10: "hsl(var(--secondary-10))",
          11: "hsl(var(--secondary-11))",
          12: "hsl(var(--secondary-12))",
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        system: {
          1: "hsl(var(--system-1))",
          2: "hsl(var(--system-2))",
          3: "hsl(var(--system-3))",
          4: "hsl(var(--system-4))",
          5: "hsl(var(--system-5))",
          6: "hsl(var(--system-6))",
          7: "hsl(var(--system-7))",
          8: "hsl(var(--system-8))",
          9: "hsl(var(--system-9))",
          10: "hsl(var(--system-10))",
          11: "hsl(var(--system-11))",
          12: "hsl(var(--system-12))",
          13: "hsl(var(--system-13))",
        },
        success: {
          1: "hsl(var(--success-1))",
          2: "hsl(var(--success-2))",
          3: "hsl(var(--success-3))",
          4: "hsl(var(--success-4))",
          5: "hsl(var(--success-5))",
          6: "hsl(var(--success-6))",
        },
        error: {
          1: "hsl(var(--error-1))",
          2: "hsl(var(--error-2))",
          3: "hsl(var(--error-3))",
          4: "hsl(var(--error-4))",
          5: "hsl(var(--error-5))",
          6: "hsl(var(--error-6))",
        },
        warning: {
          1: "hsl(var(--warning-1))",
          2: "hsl(var(--warning-2))",
          3: "hsl(var(--warning-3))",
          4: "hsl(var(--warning-4))",
          5: "hsl(var(--warning-5))",
          6: "hsl(var(--warning-6))",
        },
        rating: {
          1: "hsl(var(--rating-1))",
          2: "hsl(var(--rating-2))",
          3: "hsl(var(--rating-3))",
          4: "hsl(var(--rating-4))",
          5: "hsl(var(--rating-5))",
          6: "hsl(var(--rating-6))",
        },
        info: {
          1: "hsl(var(--info-1))",
          2: "hsl(var(--info-2))",
          3: "hsl(var(--info-3))",
          4: "hsl(var(--info-4))",
          5: "hsl(var(--info-5))",
          6: "hsl(var(--info-6))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
